### PR TITLE
cdnnow update

### PR DESCRIPTION
**Pull request by cdnnow**
fixing prices cdnnow

### CODE REVIEW

**Comment by jimaek** [comment]
Why did you modify index.html and jodihost?

**Comment by cdnnow** [comment]
We want to be the first! But if I can't - I fixed now :)

**Comment by cdnnow** [comment]
Well?

**Comment by cdnnow** [comment]
Do I need to create new pull request with new commit without modifying index.html?

**Comment by cdnnow** [comment]
Should I make a new pull request without modifying index.html?

**Comment by jimaek** [comment]
Just relax, it takes me a while to review these. Can you squash your commits into 1?

**Pull request closed without merging**
